name: Hermes
options:
  bundleIdPrefix: com.dominicsenese
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  
targets:
  Hermes:
    type: application
    platform: macOS
    sources:
      - path: Hermes
        excludes:
          - "*.entitlements"
        includes:
          - "**/*.swift"
      - path: Hermes/Hermes.icon
        type: folder
        buildPhase: resources
      - path: CLAUDE.md
        optional: true
        buildPhase: none
      - path: "Hermes App Specifications (Optimized for Claude Code Parsing).markdown"
        optional: true
        buildPhase: none
      - path: "Hermes Design System Document.markdown"
        optional: true
        buildPhase: none
      - path: "Hermes UI Feedback Instructions for Main App View and Floating Dictation Marker (Updated with New States).markdown"
        optional: true
        buildPhase: none
      - path: XCODEGEN_WORKFLOW.md
        optional: true
        buildPhase: none
      - path: project.yml
        optional: true
        buildPhase: none
      - path: scripts
        optional: true
        buildPhase: none
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dominicsenese.Hermes
        DEVELOPMENT_TEAM: "" # Add your team ID here when ready
        CODE_SIGN_ENTITLEMENTS: Hermes/Hermes.entitlements
        CODE_SIGN_STYLE: Automatic
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        SWIFT_VERSION: "5.0"
        ENABLE_PREVIEWS: true
        INFOPLIST_FILE: Hermes/Info.plist
        COMBINE_HIDPI_IMAGES: true
        CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: true
    dependencies:
      - package: WhisperKit
      - package: Supabase
    entitlements:
      path: Hermes/Hermes.entitlements
      properties:
        com.apple.security.device.microphone: true
        com.apple.security.device.audio-input: true
        com.apple.security.automation.apple-events: true
        com.apple.security.accessibility: true
      
  HermesTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - HermesTests
    dependencies:
      - target: Hermes
    settings:
      base:
        BUNDLE_LOADER: $(TEST_HOST)
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/Hermes.app/Contents/MacOS/Hermes
        
  HermesUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - HermesUITests
    dependencies:
      - target: Hermes
    settings:
      base:
        TEST_TARGET_NAME: Hermes

schemes:
  Hermes:
    build:
      targets:
        Hermes: all
        HermesTests: [test]
        HermesUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - HermesTests
        - HermesUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

fileGroups:
  - Hermes
  - HermesTests  
  - HermesUITests
  - path: Documentation
    children:
      - CLAUDE.md
      - "Hermes App Specifications (Optimized for Claude Code Parsing).markdown"
      - "Hermes Design System Document.markdown"
      - "Hermes UI Feedback Instructions for Main App View and Floating Dictation Marker (Updated with New States).markdown"
      - XCODEGEN_WORKFLOW.md
  - path: ProjectConfig
    children:
      - project.yml
  - path: Scripts
    children:
      - scripts

# Note: Additional source files will be automatically detected
# when created in the following planned structure:
# - Hermes/Core/ (DictationEngine, AudioManager, TranscriptionService, WhisperManager)
# - Hermes/UI/ (MenuBarView, DictationPopup, SettingsView, OnboardingView)  
# - Hermes/Features/ (SmartFormatting, CommandMode, WhisperingMode, CodeDictation)
# - Hermes/Team/ (SupabaseManager, AuthManager, TeamDashboard)
# - Hermes/Utilities/ (Extensions, Constants, Logger)

# Swift Package Manager dependencies
packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit
    version: 0.13.0
  Supabase:
    url: https://github.com/supabase/supabase-swift
    version: 2.5.1